version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: amangoyal9643/truecallerbackendapp:latest  # Using prebuilt Docker image
    container_name: node_app
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_DBNAME: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres  # Important: Use service name, NOT localhost
      SAMPLE_SECRET_JWT_KET: "865955bd-7b4c-4f30-acbf-e7f62833fe10"
    ports:
      - "9000:9000"

volumes:
  postgres_data:
