name: Docker Build, Push and Deploy to EC2

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Tag Docker Image
        run: |
          docker build -t amangoyal9643/truecallerbackendapp:latest .
          docker tag amangoyal9643/truecallerbackendapp:latest amangoyal9643/truecallerbackendapp:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push amangoyal9643/truecallerbackendapp:latest
          docker push amangoyal9643/truecallerbackendapp:${{ github.sha }}

  deploy:
    needs: build-and-push  # Run only after the build-and-push job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Installing Docker if not installed..."
            if ! command -v docker &> /dev/null
            then
                sudo apt update
                sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermod -aG docker $USER
            fi
            
            echo "Stopping and removing old container..."
            docker stop node_app || true
            docker rm node_app || true

                       echo "Navigating to project directory..."
            cd /home/${{ secrets.EC2_USER }}

            if [ -d "truecaller-backendapp" ]; then
              echo "Repo already exists, pulling latest changes..."
              cd truecaller-backendapp
              git pull origin main
            else
              echo "Cloning repo..."
              git clone https://github.com/Amangoyal1A/truecaller-backendapp.git
              cd truecaller-backendapp
            fi

            echo "Stopping and removing old container..."
            docker compose down || true

            echo "Running new container..."
            docker compose up --build -d

            echo "Deployment completed!"
