name: Docker Build and Push

on:
  push:
    branches: [ "dev","main" ]
  pull_request:
    branches: [ "dev","main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Tag Docker Image
        run: |
          docker build -t amangoyal9643/truecallerbackendapp:latest .
          docker tag amangoyal9643/truecallerbackendapp:latest amangoyal9643/truecallerbackendapp:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push amangoyal9643/truecallerbackendapp:latest
          docker push amangoyal9643/truecallerbackendapp:${{ github.sha }}
